function shuffleArray(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
}

let general_gallery_arr = [
  "L 4.jpg",
  "H 71.jpg",
  "LR 16.jpg",
  "HR 24.jpg",
  "LH 43.jpg",
  "L 23.jpg",
  "LH 2.jpeg",
  "LHA 64.jpg",
  "HR 11.jpg",
  "H 39.jpg",
  "A 5.jpg",
  "LHA 43.jpg",
  "HRO 7.jpg",
  "LHR 22.jpg",
  "D 19.jpg",
  "LHRO 10.jpg",
  "LH 23.jpg",
  "H 23.jpg",
  "HRO 23.jpg",
  "LHA 20.jpg",
  "LHA 66.jpg",
  "LR 18.jpg",
  "L 28.jpg",
  "LH 25.jpg",
  "LHRO 4.jpg",
  "LHA 60.jpg",
  "HRO 18.jpg",
  "HA 26.jpg",
  "L 47.jpg",
  "LHA 3.jpg",
  "H 5.jpg",
  "LHA 23.jpg",
  "LHA 19.jpg",
  "HR 31.jpg",
  "HA 30.jpg",
  "L 68.jpg",
  "LH 20.jpg",
  "D 23.jpg",
  "D 7.jpg",
  "H 15.jpg",
  "H 63.jpg",
  "HR 16.jpg",
  "H 10.jpg",
  "LH 5.jpg",
  "H 25.jpg",
  "LR 2.jpg",
  "HR 27.jpg",
  "HR 13.jpg",
  "H 19.jpg",
  "H 79.jpg",
  "HRO 10.jpg",
  "LHA 42.jpg",
  "LHR 24.jpg",
  "R 3.jpg",
  "LH 48.jpg",
  "LR 19.jpg",
  "LHRO 6.jpg",
  "HRO 16.jpg",
  "H 50.jpg",
  "LHR 17.jpg",
  "HR 33.jpg",
  "LHR 18.jpg",
  "LA 3.jpg",
  "HO 5.jpg",
  "L 16.jpg",
  "HR 32.jpg",
  "H 13.jpg",
  "HRO 13.jpg",
  "L 20.jpg",
  "LH 36.jpg",
  "W 1.jpg",
  "A 4.jpg",
  "HA 4.jpg",
  "LR 9.jpg",
  "HA 5.jpg",
  "LH 8.jpg",
  "H 44.jpg",
  "topographic1.jpg",
  "LHR 8.jpg",
  "H 65.jpg",
  "LHA 5.jpg",
  "D 21.jpg",
  "HERO 1.jpeg",
  "LHR 10.jpg",
  "H 66.jpg",
  "D 22.jpg",
  "L 56.jpg",
  "LHA 25.jpg",
  "eog-icon.png",
  "O 3.jpg",
  "R 5.jpg",
  "LHRO 12.jpg",
  "H 28.jpg",
  "LH 41.jpg",
  "LHA 41.jpg",
  "HA 21.jpg",
  "LHA 36.jpg",
  "LHR 4.jpg",
  "HRO 5.jpg",
  "LHA 45.jpg",
  "LHA 39.jpg",
  "LHR 21.jpg",
  "HRO 6.jpg",
  "LHA 8.jpg",
  "L 54.jpg",
  "LH 45.jpg",
  "H 9.jpeg",
  "LHRO 2.jpg",
  "H 52.jpg",
  "HO 1.jpg",
  "H 70.jpg",
  "L 35.jpg",
  "D 4.jpg",
  "L 41.jpg",
  "LHA 15.jpg",
  "LR 22.jpg",
  "W 3.jpg",
  "HR 37.jpg",
  "LHRO 1.jpg",
  "H 69.jpg",
  "D 18.jpg",
  "LHA 24.jpg",
  "L 15.jpg",
  "HA 3.PNG",
  "HA 1.jpg",
  "LHA 6.jpg",
  "H 58.jpg",
  "HA 22.jpg",
  "HR 21.jpg",
  "LR 12.jpg",
  "L 59.jpg",
  "H 46.jpg",
  "L 18.jpg",
  "LH 26.jpg",
  "LHR 27.jpg",
  "H 34.jpg",
  "HD 1.jpg",
  "LH 40.jpg",
  "H 27.jpg",
  "H 4.jpg",
  "HA 20.jpg",
  "H 75.jpg",
  "LH 12.jpg",
  "L 71.jpg",
  "HA 17.jpg",
  "H 7.jpg",
  "O 16.jpeg",
  "H 68.jpg",
  "LHR 19.jpg",
  "H 77.jpg",
  "LHA 52.jpg",
  "W 4.jpg",
  "D 13.jpg",
  "LH 9.jpg",
  "HR 5.jpg",
  "LR 7.jpg",
  "L 30.jpg",
  "LH 39.jpg",
  "LH 27.jpg",
  "H 40.jpg",
  "LHA 48.jpg",
  "O 13.jpg",
  "A 3.jpg",
  "LHA 65.jpg",
  "LH 24.jpg",
  "L 8.jpg",
  "LHA 40.jpg",
  "H 74.jpg",
  "LHA 2.jpg",
  "HA 7.png",
  "LHA 46.jpg",
  "HR 28.jpg",
  "L 42.jpg",
  "HRO 3.jpg",
  "H 57.jpg",
  "LHA 63.jpg",
  "D 20.jpg",
  "H 64.jpg",
  "O 15.jpg",
  "H 30.jpg",
  "H 41.jpg",
  "LHA 11.jpg",
  "LHR 28.jpg",
  "H 38.jpg",
  "L 5.jpg",
  "HRO 4.jpg",
  "L 50.jpg",
  "O 12.jpg",
  "LH 14.jpg",
  "LHRO 11.jpg",
  "HO 2.jpg",
  "H 2.jpg",
  "W 2.jpg",
  "LH 7.jpg",
  "L 12.jpg",
  "HA 29.jpg",
  "LH 13.jpg",
  "HRO 20.jpg",
  "H 78.jpg",
  "HA 10.jpg",
  "H 24.jpg",
  "HRO 14.jpeg",
  "L 36.jpg",
  "LHR 3.jpg",
  "HR 14.jpg",
  "H 62.png",
  "LO 1.jpg",
  "L 44.jpg",
  "LH 49.jpg",
  "HR 10.jpg",
  "HR 25.jpg",
  "L 33.jpg",
  "LHA 29.jpg",
  "O 9.jpg",
  "HO 8.jpg",
  "HR 34.jpg",
  "L 58.jpg",
  "LHA 7.jpg",
  "O 11.jpg",
  "HA 6.PNG",
  "LH 22.jpg",
  "LHA 28.jpg",
  "LR 15.jpg",
  "HR 19.jpg",
  "LHA 32.jpg",
  "L 51.jpg",
  "LHO 2.jpg",
  "L 63.jpg",
  "LHA 55.jpg",
  "LHRO 9.jpg",
  "O 7.jpg",
  "HR 20.jpg",
  "LHR 15.jpg",
  "HA 18.jpg",
  "LHR 6.jpg",
  "L 17.jpg",
  "LHR 20.jpg",
  "L 26.jpg",
  "HR 3.jpg",
  "H 32.jpg",
  "LHA 26.jpg",
  "LH 16.jpg",
  "O 6.jpg",
  "L 65.jpg",
  "HA 9.jpg",
  "LHA 33.jpg",
  "LRO 1.jpg",
  "LH 47.jpg",
  "HO 3.jpg",
  "D 10.jpg",
  "LH 15.jpg",
  "LR 10.jpg",
  "LH 30.jpg",
  "H 42.jpg",
  "D 3.jpg",
  "L 11.jpg",
  "LH 38.jpg",
  "D 11.jpg",
  "D 9.jpg",
  "blueprint_temp.jpg",
  "HR 30.jpg",
  "L 66.jpg",
  "L 60.PNG",
  "LHA 21.jpg",
  "HA 28.jpg",
  "D 15.jpg",
  "LHO 1.jpg",
  "H 22.jpg",
  "LHRO 13.jpg",
  "H 55.jpg",
  "O 5.jpg",
  "H 45.jpg",
  "RO 7.jpg",
  "LHA 58.jpg",
  "O 2.jpg",
  "L 72.jpg",
  "HRA 1.jpg",
  "H 6.jpg",
  "L 70.jpg",
  "H 67.jpg",
  "H 3.jpg",
  "LHO 7.jpg",
  "A 6.jpg",
  "H 61.jpg",
  "L 25.jpg",
  "LHRO 7.jpg",
  "LH 31.jpg",
  "HRO 12.jpg",
  "LHR 1.jpg",
  "LR 11.jpg",
  "LHO 3.jpg",
  "LHA 49.jpg",
  "RO 5.jpeg",
  "HA 33.jpg",
  "HRO 2.jpg",
  "D 24.jpg",
  "L 45.jpg",
  "L 61.jpg",
  "LHA 10.jpg",
  "L 21.jpg",
  "D 8.jpg",
  "HR 36.jpg",
  "LH 42.jpeg",
  "LHA 50.PNG",
  "LR 1.jpg",
  "H 47.jpg",
  "L 34.jpg",
  "HR 7.jpg",
  "RO 4.jpg",
  "R 2.jpg",
  "HR 1.jpg",
  "L 46.jpg",
  "LR 6.jpg",
  "R 1.jpg",
  "LHO 6.jpg",
  "HR 23.jpg",
  "HA 25.jpg",
  "L 49.jpg",
  "HA 13.jpg",
  "L 67.jpg",
  "O 1.jpg",
  "D 2.jpg",
  "HO 6.jpg",
  "L 43.jpg",
  "D 16.jpg",
  "H 43.jpg",
  "HR 12.jpg",
  "RO 3.jpg",
  "LHA 4.jpg",
  "L 52.jpg",
  "HRO 11.jpg",
  "H 20.jpg",
  "LH 28.jpg",
  "HA 31.jpg",
  "D 14.jpg",
  "LH 3.jpg",
  "LO 2.jpg",
  "H 17.jpg",
  "H 18.jpg",
  "HR 4.jpg",
  "LHA 16.jpg",
  "LHA 22.jpg",
  "HERO 3.jpg",
  "LH 35.jpg",
  "LHA 13.jpg",
  "L 40.jpg",
  "HA 23.jpg",
  "HRA 2.jpg",
  "LHA 51.PNG",
  "LHRO 5.jpg",
  "LHRO 8.jpg",
  "L 24.jpg",
  "LH 19.jpg",
  "LHR 23.jpg",
  "LHA 57.jpg",
  "LHR 5.jpg",
  "HA 12.jpg",
  "LHO 4.jpg",
  "LHA 53.jpg",
  "HR 35.jpg",
  "H 56.jpg",
  "L 48.jpg",
  "H 73.jpg",
  "HA 24.jpg",
  "LR 13.jpg",
  "LHA 59.jpg",
  "H 59.jpg",
  "LHA 12.jpg",
  "HERO 2.jpg",
  "LH 32.jpg",
  "L 64.jpg",
  "LHR 13.jpg",
  "O 14.jpg",
  "LHR 14.jpg",
  "HRO 9.jpg",
  "H 26.jpg",
  "LHR 26.jpg",
  "LHR 12.jpg",
  "LHR 9.jpg",
  "R 4.jpg",
  "H 8.jpg",
  "O 4.jpg",
  "LHA 34.jpg",
  "LHO 5.jpg",
  "H 36.jpg",
  "H 48.jpg",
  "HA 14.jpg",
  "L 10.jpg",
  "HA 16.jpg",
  "HR 8.jpg",
  "LR 21.jpg",
  "L 14.jpg",
  "LR 14.jpg",
  "LH 51.jpg",
  "H 49.jpg",
  "LHA 27.jpg",
  "HA 8.jpg",
  "HR 6.jpg",
  "L 62.jpg",
  "LA 1.jpg",
  "R 6.jpg",
  "LR 8.jpg",
  "LH 6.jpg",
  "LHA 38.jpg",
  "HA 2.jpg",
  "HO 4.jpg",
  "LH 37.jpg",
  "L 69.jpg",
  "LH 54.jpg",
  "LHR 11.jpg",
  "L 3.jpg",
  "L 53.jpg",
  "LH 33.jpg",
  "HA 15.jpg",
  "LH 21.jpg",
  "HR 9.jpg",
  "HR 17.jpg",
  "LHA 44.jpg",
  "LHA 18.jpg",
  "L 55.jpg",
  "H 14.jpg",
  "LH 44.jpg",
  "L 32.jpg",
  "HRO 17.jpg",
  "L 57.jpg",
  "HRO 1.jpg",
  "HR 38.JPG",
  "L 1.jpg",
  "HR 26.jpg",
  "H 16.jpg",
  "L 6.jpg",
  "LHA 17.jpg",
  "LHR 25.jpg",
  "LHA 31.jpg",
  "LR 20.jpg",
  "H 51.jpg",
  "LHA 56.jpg",
  "L 73.jpg",
  "LH 4.jpg",
  "L 7.jpg",
  "HR 2.jpg",
  "LR 5.jpg",
  "LH 10.jpg",
  "essence of green logo 1.png",
  "L 29.jpg",
  "LHA 30.jpg",
  "LHA 9.jpg",
  "O 8.jpg",
  "HRO 21.jpg",
  "H 31.jpg",
  "HRO 22.jpg",
  "L 39.jpg",
  "D 5.jpg",
  "HRO 19.jpg",
  "L 13.jpg",
  "LHR 2.jpg",
  "H 1.jpg",
  "LHR 16.jpg",
  "RO 2.jpg",
  "RO 1.jpg",
  "H 12.jpg",
  "HR 29.jpg",
  "LHA 14.jpg",
  "D 12.jpg",
  "LHA 37.jpg",
  "H 11.jpg",
  "A 1.jpg",
  "LHA 54.jpg",
  "HO 7.jpg",
  "D-25.jpg",
  "LH 17.jpg",
  "LHR 7.jpg",
  "LR 17.jpg",
  "LHA 1.jpg",
  "LHA 62.jpg",
  "LHA 61.jpg",
  "L 9.jpg",
  "D 17.jpg",
  "LA 2.jpg",
  "HA 27.jpg",
  "L 22.jpg",
  "LH 46.jpg",
  "L 2.jpg",
  "A 2.jpg",
  "LH 18.jpg",
  "LH 53.jpg",
  "HA 11.jpg",
  "LHA 35.jpg",
  "H 35.jpg",
  "HR 15.jpg",
  "H 60.jpg",
  "eog-logo-text-white.png",
  "HA 32.jpg",
  "L 37.jpg",
  "HRO 15.jpg",
  "LH 11.jpg",
  "H 72.jpg",
  "L 38.jpg",
  "H 53.jpg",
  "HR 22.jpg",
  "D 1.jpg",
  "LH 34.jpg",
  "LR 3.jpg",
  "H 29.jpg",
  "LH 52.jpg",
  "LAO 1.jpg",
  "O 10.jpg",
  "L 31.jpg",
  "LR 4.jpg",
  "H 54.jpg",
  "HR 18.jpg",
  "L 19.jpg",
  "H 33.jpg",
  "H 21.jpg",
  "LH 1.jpg",
  "D 6.jpg",
  "L 27.jpg",
  "LHRO 3.jpg",
  "LHA 47.jpg",
  "RO 6.jpg",
  "H 76.jpg",
  "LH 29.jpg",
  "H 37.jpg",
  "HA 19.jpg",
  "HRO 8.jpg",
];
shuffleArray(general_gallery_arr);

let landscape_gallery_arr = [
  "L 1.jpg",
  "L 10.jpg",
  "L 11.jpg",
  "L 12.jpg",
  "L 13.jpg",
  "L 14.jpg",
  "L 15.jpg",
  "L 16.jpg",
  "L 17.jpg",
  "L 18.jpg",
  "L 19.jpg",
  "L 2.jpg",
  "L 20.jpg",
  "L 21.jpg",
  "L 22.jpg",
  "L 23.jpg",
  "L 24.jpg",
  "L 25.jpg",
  "L 26.jpg",
  "L 27.jpg",
  "L 28.jpg",
  "L 29.jpg",
  "L 3.jpg",
  "L 30.jpg",
  "L 31.jpg",
  "L 32.jpg",
  "L 33.jpg",
  "L 34.jpg",
  "L 35.jpg",
  "L 36.jpg",
  "L 37.jpg",
  "L 38.jpg",
  "L 39.jpg",
  "L 4.jpg",
  "L 40.jpg",
  "L 41.jpg",
  "L 42.jpg",
  "L 43.jpg",
  "L 44.jpg",
  "L 45.jpg",
  "L 46.jpg",
  "L 47.jpg",
  "L 48.jpg",
  "L 49.jpg",
  "L 5.jpg",
  "L 50.jpg",
  "L 51.jpg",
  "L 52.jpg",
  "L 53.jpg",
  "L 54.jpg",
  "L 55.jpg",
  "L 56.jpg",
  "L 57.jpg",
  "L 58.jpg",
  "L 59.jpg",
  "L 6.jpg",
  "L 60.PNG",
  "L 61.jpg",
  "L 62.jpg",
  "L 63.jpg",
  "L 64.jpg",
  "L 65.jpg",
  "L 66.jpg",
  "L 67.jpg",
  "L 68.jpg",
  "L 69.jpg",
  "L 7.jpg",
  "L 70.jpg",
  "L 71.jpg",
  "L 72.jpg",
  "L 73.jpg",
  "L 8.jpg",
  "L 9.jpg",
  "LA 1.jpg",
  "LA 2.jpg",
  "LA 3.jpg",
  "LAO 1.jpg",
  "LH 1.jpg",
  "LH 10.jpg",
  "LH 11.jpg",
  "LH 12.jpg",
  "LH 13.jpg",
  "LH 14.jpg",
  "LH 15.jpg",
  "LH 16.jpg",
  "LH 17.jpg",
  "LH 18.jpg",
  "LH 19.jpg",
  "LH 2.jpeg",
  "LH 20.jpg",
  "LH 21.jpg",
  "LH 22.jpg",
  "LH 23.jpg",
  "LH 24.jpg",
  "LH 25.jpg",
  "LH 26.jpg",
  "LH 27.jpg",
  "LH 28.jpg",
  "LH 29.jpg",
  "LH 3.jpg",
  "LH 30.jpg",
  "LH 31.jpg",
  "LH 32.jpg",
  "LH 33.jpg",
  "LH 34.jpg",
  "LH 35.jpg",
  "LH 36.jpg",
  "LH 37.jpg",
  "LH 38.jpg",
  "LH 39.jpg",
  "LH 4.jpg",
  "LH 40.jpg",
  "LH 41.jpg",
  "LH 42.jpeg",
  "LH 43.jpg",
  "LH 44.jpg",
  "LH 45.jpg",
  "LH 46.jpg",
  "LH 47.jpg",
  "LH 48.jpg",
  "LH 49.jpg",
  "LH 5.jpg",
  "LH 51.jpg",
  "LH 52.jpg",
  "LH 53.jpg",
  "LH 54.jpg",
  "LH 6.jpg",
  "LH 7.jpg",
  "LH 8.jpg",
  "LH 9.jpg",
  "LHA 1.jpg",
  "LHA 10.jpg",
  "LHA 11.jpg",
  "LHA 12.jpg",
  "LHA 13.jpg",
  "LHA 14.jpg",
  "LHA 15.jpg",
  "LHA 16.jpg",
  "LHA 17.jpg",
  "LHA 18.jpg",
  "LHA 19.jpg",
  "LHA 2.jpg",
  "LHA 20.jpg",
  "LHA 21.jpg",
  "LHA 22.jpg",
  "LHA 23.jpg",
  "LHA 24.jpg",
  "LHA 25.jpg",
  "LHA 26.jpg",
  "LHA 27.jpg",
  "LHA 28.jpg",
  "LHA 29.jpg",
  "LHA 3.jpg",
  "LHA 30.jpg",
  "LHA 31.jpg",
  "LHA 32.jpg",
  "LHA 33.jpg",
  "LHA 34.jpg",
  "LHA 35.jpg",
  "LHA 36.jpg",
  "LHA 37.jpg",
  "LHA 38.jpg",
  "LHA 39.jpg",
  "LHA 4.jpg",
  "LHA 40.jpg",
  "LHA 41.jpg",
  "LHA 42.jpg",
  "LHA 43.jpg",
  "LHA 44.jpg",
  "LHA 45.jpg",
  "LHA 46.jpg",
  "LHA 47.jpg",
  "LHA 48.jpg",
  "LHA 49.jpg",
  "LHA 5.jpg",
  "LHA 50.PNG",
  "LHA 51.PNG",
  "LHA 52.jpg",
  "LHA 53.jpg",
  "LHA 54.jpg",
  "LHA 55.jpg",
  "LHA 56.jpg",
  "LHA 57.jpg",
  "LHA 58.jpg",
  "LHA 59.jpg",
  "LHA 6.jpg",
  "LHA 60.jpg",
  "LHA 61.jpg",
  "LHA 62.jpg",
  "LHA 63.jpg",
  "LHA 64.jpg",
  "LHA 65.jpg",
  "LHA 66.jpg",
  "LHA 7.jpg",
  "LHA 8.jpg",
  "LHA 9.jpg",
  "LHO 1.jpg",
  "LHO 2.jpg",
  "LHO 3.jpg",
  "LHO 4.jpg",
  "LHO 5.jpg",
  "LHO 6.jpg",
  "LHO 7.jpg",
  "LHR 1.jpg",
  "LHR 10.jpg",
  "LHR 11.jpg",
  "LHR 12.jpg",
  "LHR 13.jpg",
  "LHR 14.jpg",
  "LHR 15.jpg",
  "LHR 16.jpg",
  "LHR 17.jpg",
  "LHR 18.jpg",
  "LHR 19.jpg",
  "LHR 2.jpg",
  "LHR 20.jpg",
  "LHR 21.jpg",
  "LHR 22.jpg",
  "LHR 23.jpg",
  "LHR 24.jpg",
  "LHR 25.jpg",
  "LHR 26.jpg",
  "LHR 27.jpg",
  "LHR 28.jpg",
  "LHR 3.jpg",
  "LHR 4.jpg",
  "LHR 5.jpg",
  "LHR 6.jpg",
  "LHR 7.jpg",
  "LHR 8.jpg",
  "LHR 9.jpg",
  "LHRO 1.jpg",
  "LHRO 10.jpg",
  "LHRO 11.jpg",
  "LHRO 12.jpg",
  "LHRO 13.jpg",
  "LHRO 2.jpg",
  "LHRO 3.jpg",
  "LHRO 4.jpg",
  "LHRO 5.jpg",
  "LHRO 6.jpg",
  "LHRO 7.jpg",
  "LHRO 8.jpg",
  "LHRO 9.jpg",
  "LO 1.jpg",
  "LO 2.jpg",
  "LR 1.jpg",
  "LR 10.jpg",
  "LR 11.jpg",
  "LR 12.jpg",
  "LR 13.jpg",
  "LR 14.jpg",
  "LR 15.jpg",
  "LR 16.jpg",
  "LR 17.jpg",
  "LR 18.jpg",
  "LR 19.jpg",
  "LR 2.jpg",
  "LR 20.jpg",
  "LR 21.jpg",
  "LR 22.jpg",
  "LR 3.jpg",
  "LR 4.jpg",
  "LR 5.jpg",
  "LR 6.jpg",
  "LR 7.jpg",
  "LR 8.jpg",
  "LR 9.jpg",
  "LRO 1.jpg",
];
shuffleArray(landscape_gallery_arr);

let hardscape_gallery_arr = [
  "H 1.jpg",
  "H 10.jpg",
  "H 11.jpg",
  "H 12.jpg",
  "H 13.jpg",
  "H 14.jpg",
  "H 15.jpg",
  "H 16.jpg",
  "H 17.jpg",
  "H 18.jpg",
  "H 19.jpg",
  "H 2.jpg",
  "H 20.jpg",
  "H 21.jpg",
  "H 22.jpg",
  "H 23.jpg",
  "H 24.jpg",
  "H 25.jpg",
  "H 26.jpg",
  "H 27.jpg",
  "H 28.jpg",
  "H 29.jpg",
  "H 3.jpg",
  "H 30.jpg",
  "H 31.jpg",
  "H 32.jpg",
  "H 33.jpg",
  "H 34.jpg",
  "H 35.jpg",
  "H 36.jpg",
  "H 37.jpg",
  "H 38.jpg",
  "H 39.jpg",
  "H 4.jpg",
  "H 40.jpg",
  "H 41.jpg",
  "H 42.jpg",
  "H 43.jpg",
  "H 44.jpg",
  "H 45.jpg",
  "H 46.jpg",
  "H 47.jpg",
  "H 48.jpg",
  "H 49.jpg",
  "H 5.jpg",
  "H 50.jpg",
  "H 51.jpg",
  "H 52.jpg",
  "H 53.jpg",
  "H 54.jpg",
  "H 55.jpg",
  "H 56.jpg",
  "H 57.jpg",
  "H 58.jpg",
  "H 59.jpg",
  "H 6.jpg",
  "H 60.jpg",
  "H 61.jpg",
  "H 62.png",
  "H 63.jpg",
  "H 64.jpg",
  "H 65.jpg",
  "H 66.jpg",
  "H 67.jpg",
  "H 68.jpg",
  "H 69.jpg",
  "H 7.jpg",
  "H 70.jpg",
  "H 71.jpg",
  "H 72.jpg",
  "H 73.jpg",
  "H 74.jpg",
  "H 75.jpg",
  "H 76.jpg",
  "H 77.jpg",
  "H 78.jpg",
  "H 79.jpg",
  "H 8.jpg",
  "H 9.jpeg",
  "HA 1.jpg",
  "HA 10.jpg",
  "HA 11.jpg",
  "HA 12.jpg",
  "HA 13.jpg",
  "HA 14.jpg",
  "HA 15.jpg",
  "HA 16.jpg",
  "HA 17.jpg",
  "HA 18.jpg",
  "HA 19.jpg",
  "HA 2.jpg",
  "HA 20.jpg",
  "HA 21.jpg",
  "HA 22.jpg",
  "HA 23.jpg",
  "HA 24.jpg",
  "HA 25.jpg",
  "HA 26.jpg",
  "HA 27.jpg",
  "HA 28.jpg",
  "HA 29.jpg",
  "HA 3.PNG",
  "HA 30.jpg",
  "HA 31.jpg",
  "HA 32.jpg",
  "HA 33.jpg",
  "HA 4.jpg",
  "HA 5.jpg",
  "HA 6.PNG",
  "HA 7.png",
  "HA 8.jpg",
  "HA 9.jpg",
  "HD 1.jpg",
  "HERO 1.jpeg",
  "HERO 2.jpg",
  "HERO 3.jpg",
  "HO 1.jpg",
  "HO 2.jpg",
  "HO 3.jpg",
  "HO 4.jpg",
  "HO 5.jpg",
  "HO 6.jpg",
  "HO 7.jpg",
  "HO 8.jpg",
  "HR 1.jpg",
  "HR 10.jpg",
  "HR 11.jpg",
  "HR 12.jpg",
  "HR 13.jpg",
  "HR 14.jpg",
  "HR 15.jpg",
  "HR 16.jpg",
  "HR 17.jpg",
  "HR 18.jpg",
  "HR 19.jpg",
  "HR 2.jpg",
  "HR 20.jpg",
  "HR 21.jpg",
  "HR 22.jpg",
  "HR 23.jpg",
  "HR 24.jpg",
  "HR 25.jpg",
  "HR 26.jpg",
  "HR 27.jpg",
  "HR 28.jpg",
  "HR 29.jpg",
  "HR 3.jpg",
  "HR 30.jpg",
  "HR 31.jpg",
  "HR 32.jpg",
  "HR 33.jpg",
  "HR 34.jpg",
  "HR 35.jpg",
  "HR 36.jpg",
  "HR 37.jpg",
  "HR 38.JPG",
  "HR 4.jpg",
  "HR 5.jpg",
  "HR 6.jpg",
  "HR 7.jpg",
  "HR 8.jpg",
  "HR 9.jpg",
  "HRA 1.jpg",
  "HRA 2.jpg",
  "HRO 1.jpg",
  "HRO 10.jpg",
  "HRO 11.jpg",
  "HRO 12.jpg",
  "HRO 13.jpg",
  "HRO 14.jpeg",
  "HRO 15.jpg",
  "HRO 16.jpg",
  "HRO 17.jpg",
  "HRO 18.jpg",
  "HRO 19.jpg",
  "HRO 2.jpg",
  "HRO 20.jpg",
  "HRO 21.jpg",
  "HRO 22.jpg",
  "HRO 23.jpg",
  "HRO 3.jpg",
  "HRO 4.jpg",
  "HRO 5.jpg",
  "HRO 6.jpg",
  "HRO 7.jpg",
  "HRO 8.jpg",
  "HRO 9.jpg",
  "LH 1.jpg",
  "LH 10.jpg",
  "LH 11.jpg",
  "LH 12.jpg",
  "LH 13.jpg",
  "LH 14.jpg",
  "LH 15.jpg",
  "LH 16.jpg",
  "LH 17.jpg",
  "LH 18.jpg",
  "LH 19.jpg",
  "LH 2.jpeg",
  "LH 20.jpg",
  "LH 21.jpg",
  "LH 22.jpg",
  "LH 23.jpg",
  "LH 24.jpg",
  "LH 25.jpg",
  "LH 26.jpg",
  "LH 27.jpg",
  "LH 28.jpg",
  "LH 29.jpg",
  "LH 3.jpg",
  "LH 30.jpg",
  "LH 31.jpg",
  "LH 32.jpg",
  "LH 33.jpg",
  "LH 34.jpg",
  "LH 35.jpg",
  "LH 36.jpg",
  "LH 37.jpg",
  "LH 38.jpg",
  "LH 39.jpg",
  "LH 4.jpg",
  "LH 40.jpg",
  "LH 41.jpg",
  "LH 42.jpeg",
  "LH 43.jpg",
  "LH 44.jpg",
  "LH 45.jpg",
  "LH 46.jpg",
  "LH 47.jpg",
  "LH 48.jpg",
  "LH 49.jpg",
  "LH 5.jpg",
  "LH 51.jpg",
  "LH 52.jpg",
  "LH 53.jpg",
  "LH 54.jpg",
  "LH 6.jpg",
  "LH 7.jpg",
  "LH 8.jpg",
  "LH 9.jpg",
  "LHA 1.jpg",
  "LHA 10.jpg",
  "LHA 11.jpg",
  "LHA 12.jpg",
  "LHA 13.jpg",
  "LHA 14.jpg",
  "LHA 15.jpg",
  "LHA 16.jpg",
  "LHA 17.jpg",
  "LHA 18.jpg",
  "LHA 19.jpg",
  "LHA 2.jpg",
  "LHA 20.jpg",
  "LHA 21.jpg",
  "LHA 22.jpg",
  "LHA 23.jpg",
  "LHA 24.jpg",
  "LHA 25.jpg",
  "LHA 26.jpg",
  "LHA 27.jpg",
  "LHA 28.jpg",
  "LHA 29.jpg",
  "LHA 3.jpg",
  "LHA 30.jpg",
  "LHA 31.jpg",
  "LHA 32.jpg",
  "LHA 33.jpg",
  "LHA 34.jpg",
  "LHA 35.jpg",
  "LHA 36.jpg",
  "LHA 37.jpg",
  "LHA 38.jpg",
  "LHA 39.jpg",
  "LHA 4.jpg",
  "LHA 40.jpg",
  "LHA 41.jpg",
  "LHA 42.jpg",
  "LHA 43.jpg",
  "LHA 44.jpg",
  "LHA 45.jpg",
  "LHA 46.jpg",
  "LHA 47.jpg",
  "LHA 48.jpg",
  "LHA 49.jpg",
  "LHA 5.jpg",
  "LHA 50.PNG",
  "LHA 51.PNG",
  "LHA 52.jpg",
  "LHA 53.jpg",
  "LHA 54.jpg",
  "LHA 55.jpg",
  "LHA 56.jpg",
  "LHA 57.jpg",
  "LHA 58.jpg",
  "LHA 59.jpg",
  "LHA 6.jpg",
  "LHA 60.jpg",
  "LHA 61.jpg",
  "LHA 62.jpg",
  "LHA 63.jpg",
  "LHA 64.jpg",
  "LHA 65.jpg",
  "LHA 66.jpg",
  "LHA 7.jpg",
  "LHA 8.jpg",
  "LHA 9.jpg",
  "LHO 1.jpg",
  "LHO 2.jpg",
  "LHO 3.jpg",
  "LHO 4.jpg",
  "LHO 5.jpg",
  "LHO 6.jpg",
  "LHO 7.jpg",
  "LHR 1.jpg",
  "LHR 10.jpg",
  "LHR 11.jpg",
  "LHR 12.jpg",
  "LHR 13.jpg",
  "LHR 14.jpg",
  "LHR 15.jpg",
  "LHR 16.jpg",
  "LHR 17.jpg",
  "LHR 18.jpg",
  "LHR 19.jpg",
  "LHR 2.jpg",
  "LHR 20.jpg",
  "LHR 21.jpg",
  "LHR 22.jpg",
  "LHR 23.jpg",
  "LHR 24.jpg",
  "LHR 25.jpg",
  "LHR 26.jpg",
  "LHR 27.jpg",
  "LHR 28.jpg",
  "LHR 3.jpg",
  "LHR 4.jpg",
  "LHR 5.jpg",
  "LHR 6.jpg",
  "LHR 7.jpg",
  "LHR 8.jpg",
  "LHR 9.jpg",
  "LHRO 1.jpg",
  "LHRO 10.jpg",
  "LHRO 11.jpg",
  "LHRO 12.jpg",
  "LHRO 13.jpg",
  "LHRO 2.jpg",
  "LHRO 3.jpg",
  "LHRO 4.jpg",
  "LHRO 5.jpg",
  "LHRO 6.jpg",
  "LHRO 7.jpg",
  "LHRO 8.jpg",
  "LHRO 9.jpg",
];
shuffleArray(hardscape_gallery_arr);

let rooftops_courtyards_gallery_arr = [
  "HERO 1.jpeg",
  "HERO 2.jpg",
  "HERO 3.jpg",
  "HR 1.jpg",
  "HR 10.jpg",
  "HR 11.jpg",
  "HR 12.jpg",
  "HR 13.jpg",
  "HR 14.jpg",
  "HR 15.jpg",
  "HR 16.jpg",
  "HR 17.jpg",
  "HR 18.jpg",
  "HR 19.jpg",
  "HR 2.jpg",
  "HR 20.jpg",
  "HR 21.jpg",
  "HR 22.jpg",
  "HR 23.jpg",
  "HR 24.jpg",
  "HR 25.jpg",
  "HR 26.jpg",
  "HR 27.jpg",
  "HR 28.jpg",
  "HR 29.jpg",
  "HR 3.jpg",
  "HR 30.jpg",
  "HR 31.jpg",
  "HR 32.jpg",
  "HR 33.jpg",
  "HR 34.jpg",
  "HR 35.jpg",
  "HR 36.jpg",
  "HR 37.jpg",
  "HR 38.JPG",
  "HR 4.jpg",
  "HR 5.jpg",
  "HR 6.jpg",
  "HR 7.jpg",
  "HR 8.jpg",
  "HR 9.jpg",
  "HRA 1.jpg",
  "HRA 2.jpg",
  "HRO 1.jpg",
  "HRO 10.jpg",
  "HRO 11.jpg",
  "HRO 12.jpg",
  "HRO 13.jpg",
  "HRO 14.jpeg",
  "HRO 15.jpg",
  "HRO 16.jpg",
  "HRO 17.jpg",
  "HRO 18.jpg",
  "HRO 19.jpg",
  "HRO 2.jpg",
  "HRO 20.jpg",
  "HRO 21.jpg",
  "HRO 22.jpg",
  "HRO 23.jpg",
  "HRO 3.jpg",
  "HRO 4.jpg",
  "HRO 5.jpg",
  "HRO 6.jpg",
  "HRO 7.jpg",
  "HRO 8.jpg",
  "HRO 9.jpg",
  "LHR 1.jpg",
  "LHR 10.jpg",
  "LHR 11.jpg",
  "LHR 12.jpg",
  "LHR 13.jpg",
  "LHR 14.jpg",
  "LHR 15.jpg",
  "LHR 16.jpg",
  "LHR 17.jpg",
  "LHR 18.jpg",
  "LHR 19.jpg",
  "LHR 2.jpg",
  "LHR 20.jpg",
  "LHR 21.jpg",
  "LHR 22.jpg",
  "LHR 23.jpg",
  "LHR 24.jpg",
  "LHR 25.jpg",
  "LHR 26.jpg",
  "LHR 27.jpg",
  "LHR 28.jpg",
  "LHR 3.jpg",
  "LHR 4.jpg",
  "LHR 5.jpg",
  "LHR 6.jpg",
  "LHR 7.jpg",
  "LHR 8.jpg",
  "LHR 9.jpg",
  "LHRO 1.jpg",
  "LHRO 10.jpg",
  "LHRO 11.jpg",
  "LHRO 12.jpg",
  "LHRO 13.jpg",
  "LHRO 2.jpg",
  "LHRO 3.jpg",
  "LHRO 4.jpg",
  "LHRO 5.jpg",
  "LHRO 6.jpg",
  "LHRO 7.jpg",
  "LHRO 8.jpg",
  "LHRO 9.jpg",
  "LR 1.jpg",
  "LR 10.jpg",
  "LR 11.jpg",
  "LR 12.jpg",
  "LR 13.jpg",
  "LR 14.jpg",
  "LR 15.jpg",
  "LR 16.jpg",
  "LR 17.jpg",
  "LR 18.jpg",
  "LR 19.jpg",
  "LR 2.jpg",
  "LR 20.jpg",
  "LR 21.jpg",
  "LR 22.jpg",
  "LR 3.jpg",
  "LR 4.jpg",
  "LR 5.jpg",
  "LR 6.jpg",
  "LR 7.jpg",
  "LR 8.jpg",
  "LR 9.jpg",
  "LRO 1.jpg",
  "R 1.jpg",
  "R 2.jpg",
  "R 3.jpg",
  "R 4.jpg",
  "R 5.jpg",
  "R 6.jpg",
  "RO 1.jpg",
  "RO 2.jpg",
  "RO 3.jpg",
  "RO 4.jpg",
  "RO 5.jpeg",
  "RO 6.jpg",
  "RO 7.jpg",
];
shuffleArray(rooftops_courtyards_gallery_arr);

let water_features_gallery_arr = [
  "A 1.jpg",
  "A 2.jpg",
  "A 3.jpg",
  "A 4.jpg",
  "A 5.jpg",
  "A 6.jpg",
  "HA 1.jpg",
  "HA 10.jpg",
  "HA 11.jpg",
  "HA 12.jpg",
  "HA 13.jpg",
  "HA 14.jpg",
  "HA 15.jpg",
  "HA 16.jpg",
  "HA 17.jpg",
  "HA 18.jpg",
  "HA 19.jpg",
  "HA 2.jpg",
  "HA 20.jpg",
  "HA 21.jpg",
  "HA 22.jpg",
  "HA 23.jpg",
  "HA 24.jpg",
  "HA 25.jpg",
  "HA 26.jpg",
  "HA 27.jpg",
  "HA 28.jpg",
  "HA 29.jpg",
  "HA 3.PNG",
  "HA 30.jpg",
  "HA 31.jpg",
  "HA 32.jpg",
  "HA 33.jpg",
  "HA 4.jpg",
  "HA 5.jpg",
  "HA 6.PNG",
  "HA 7.png",
  "HA 8.jpg",
  "HA 9.jpg",
  "HRA 1.jpg",
  "HRA 2.jpg",
  "LA 1.jpg",
  "LA 2.jpg",
  "LA 3.jpg",
  "LAO 1.jpg",
  "LHA 1.jpg",
  "LHA 10.jpg",
  "LHA 11.jpg",
  "LHA 12.jpg",
  "LHA 13.jpg",
  "LHA 14.jpg",
  "LHA 15.jpg",
  "LHA 16.jpg",
  "LHA 17.jpg",
  "LHA 18.jpg",
  "LHA 19.jpg",
  "LHA 2.jpg",
  "LHA 20.jpg",
  "LHA 21.jpg",
  "LHA 22.jpg",
  "LHA 23.jpg",
  "LHA 24.jpg",
  "LHA 25.jpg",
  "LHA 26.jpg",
  "LHA 27.jpg",
  "LHA 28.jpg",
  "LHA 29.jpg",
  "LHA 3.jpg",
  "LHA 30.jpg",
  "LHA 31.jpg",
  "LHA 32.jpg",
  "LHA 33.jpg",
  "LHA 34.jpg",
  "LHA 35.jpg",
  "LHA 36.jpg",
  "LHA 37.jpg",
  "LHA 38.jpg",
  "LHA 39.jpg",
  "LHA 4.jpg",
  "LHA 40.jpg",
  "LHA 41.jpg",
  "LHA 42.jpg",
  "LHA 43.jpg",
  "LHA 44.jpg",
  "LHA 45.jpg",
  "LHA 46.jpg",
  "LHA 47.jpg",
  "LHA 48.jpg",
  "LHA 49.jpg",
  "LHA 5.jpg",
  "LHA 50.PNG",
  "LHA 51.PNG",
  "LHA 52.jpg",
  "LHA 53.jpg",
  "LHA 54.jpg",
  "LHA 55.jpg",
  "LHA 56.jpg",
  "LHA 57.jpg",
  "LHA 58.jpg",
  "LHA 59.jpg",
  "LHA 6.jpg",
  "LHA 60.jpg",
  "LHA 61.jpg",
  "LHA 62.jpg",
  "LHA 63.jpg",
  "LHA 64.jpg",
  "LHA 65.jpg",
  "LHA 66.jpg",
  "LHA 7.jpg",
  "LHA 8.jpg",
  "LHA 9.jpg",
];
shuffleArray(water_features_gallery_arr);

let custom_woodwork_gallery_arr = [
  "HERO 1.jpeg",
  "HERO 2.jpg",
  "HERO 3.jpg",
  "HO 1.jpg",
  "HO 2.jpg",
  "HO 3.jpg",
  "HO 4.jpg",
  "HO 5.jpg",
  "HO 6.jpg",
  "HO 7.jpg",
  "HO 8.jpg",
  "HRO 1.jpg",
  "HRO 10.jpg",
  "HRO 11.jpg",
  "HRO 12.jpg",
  "HRO 13.jpg",
  "HRO 14.jpeg",
  "HRO 15.jpg",
  "HRO 16.jpg",
  "HRO 17.jpg",
  "HRO 18.jpg",
  "HRO 19.jpg",
  "HRO 2.jpg",
  "HRO 20.jpg",
  "HRO 21.jpg",
  "HRO 22.jpg",
  "HRO 23.jpg",
  "HRO 3.jpg",
  "HRO 4.jpg",
  "HRO 5.jpg",
  "HRO 6.jpg",
  "HRO 7.jpg",
  "HRO 8.jpg",
  "HRO 9.jpg",
  "LAO 1.jpg",
  "LHO 1.jpg",
  "LHO 2.jpg",
  "LHO 3.jpg",
  "LHO 4.jpg",
  "LHO 5.jpg",
  "LHO 6.jpg",
  "LHO 7.jpg",
  "LHRO 1.jpg",
  "LHRO 10.jpg",
  "LHRO 11.jpg",
  "LHRO 12.jpg",
  "LHRO 13.jpg",
  "LHRO 2.jpg",
  "LHRO 3.jpg",
  "LHRO 4.jpg",
  "LHRO 5.jpg",
  "LHRO 6.jpg",
  "LHRO 7.jpg",
  "LHRO 8.jpg",
  "LHRO 9.jpg",
  "LO 1.jpg",
  "LO 2.jpg",
  "LRO 1.jpg",
  "O 1.jpg",
  "O 10.jpg",
  "O 11.jpg",
  "O 12.jpg",
  "O 13.jpg",
  "O 14.jpg",
  "O 15.jpg",
  "O 16.jpeg",
  "O 2.jpg",
  "O 3.jpg",
  "O 4.jpg",
  "O 5.jpg",
  "O 6.jpg",
  "O 7.jpg",
  "O 8.jpg",
  "O 9.jpg",
  "RO 1.jpg",
  "RO 2.jpg",
  "RO 3.jpg",
  "RO 4.jpg",
  "RO 5.jpeg",
  "RO 6.jpg",
  "RO 7.jpg",
];
shuffleArray(custom_woodwork_gallery_arr);

let drainage_gallery_arr = [
  "D 1.jpg",
  "D 10.jpg",
  "D 11.jpg",
  "D 12.jpg",
  "D 13.jpg",
  "D 14.jpg",
  "D 15.jpg",
  "D 16.jpg",
  "D 17.jpg",
  "D 18.jpg",
  "D 19.jpg",
  "D 2.jpg",
  "D 20.jpg",
  "D 21.jpg",
  "D 22.jpg",
  "D 23.jpg",
  "D 24.jpg",
  "D 3.jpg",
  "D 4.jpg",
  "D 5.jpg",
  "D 6.jpg",
  "D 7.jpg",
  "D 8.jpg",
  "D 9.jpg",
  "D-25.jpg",
  "HD 1.jpg",
];
shuffleArray(drainage_gallery_arr);

let images = [];
let currentIndex = 0;

// Initialize the gallery on page load
document.addEventListener("DOMContentLoaded", () => {
  // Function to initialize a gallery if its grid ID exists
  const safeInitGallery = (path, id, imageArray) => {
    const galleryElement = document.getElementById(`${id}-grid`);
    if (galleryElement) {
      initGallery(path, id, imageArray);
    }
  };

  // Initialize galleries
  safeInitGallery("img/", "landscape-gallery", landscape_gallery_arr);

  safeInitGallery("img/", "hardscape-gallery", hardscape_gallery_arr);

  safeInitGallery(
    "img/",
    "rooftops-courtyards-gallery",
    rooftops_courtyards_gallery_arr
  );

  safeInitGallery("img/", "water-features-gallery", water_features_gallery_arr);

  safeInitGallery(
    "img/",
    "custom-woodwork-gallery",
    custom_woodwork_gallery_arr
  );

  safeInitGallery("img/", "drainage-gallery", drainage_gallery_arr);

  safeInitGallery("img/", "general-gallery", general_gallery_arr);
});

// Function to initialize a gallery
function initGallery(folderPath, galleryId, imageFilenames) {
  const galleryGrid = document.getElementById(`${galleryId}-grid`);

  if (!galleryGrid) {
    console.error(`Gallery grid with ID '${galleryId}-grid' not found.`);
    return;
  }

  if (galleryGrid.getAttribute("data-initialized") === "true") {
    return;
  }

  galleryGrid.setAttribute("data-initialized", "true");

  images = imageFilenames;

  imageFilenames.forEach((filename, index) => {
    const imgElement = document.createElement("img");
    imgElement.src = `${folderPath}${filename}`;
    imgElement.alt = `Gallery Image ${index + 1}`;
    imgElement.className = "service-item__gallery-item";
    imgElement.style.opacity = 0;
    imgElement.style.transition =
      "opacity 0.3s ease-in-out, transform 0.3s ease";

    // Wait until the image is fully loaded
    imgElement.onload = () => {
      imgElement.style.opacity = 1;
    };

    imgElement.onerror = () => {
      console.error(`Error loading image: ${filename}`);
    };

    imgElement.setAttribute("onclick", `openModal(${index}, '${galleryId}')`);
    galleryGrid.appendChild(imgElement);
  });
}

// Open modal and display the selected image
function openModal(index, galleryId) {
  const galleryGrid = document.getElementById(`${galleryId}-grid`);
  if (!galleryGrid) {
    console.error(`Gallery grid with ID '${galleryId}-grid' not found.`);
    return;
  }

  // Get images array from the gallery grid
  const images = Array.from(galleryGrid.querySelectorAll("img")).map(
    (img) => img.src
  );

  const modal = document.getElementById(`${galleryId}-modal`);
  const modalImage = document.getElementById(`${galleryId}-modalImage`);

  if (!modal || !modalImage) {
    console.error(`Modal or modalImage for gallery '${galleryId}' not found.`);
    return;
  }

  modal.style.display = "flex";
  modalImage.src = images[index];

  currentIndex = index;

  // Keyboard navigation
  const handleKeyDown = (event) => {
    if (event.key === "ArrowRight") {
      changeImage(1, galleryId);
    } else if (event.key === "ArrowLeft") {
      changeImage(-1, galleryId);
    } else if (event.key === "Escape") {
      closeModal(galleryId);
    }
  };

  document.addEventListener("keydown", handleKeyDown);

  modal.onclick = (event) => {
    if (event.target === modal) {
      closeModal(galleryId);
      document.removeEventListener("keydown", handleKeyDown);
    }
  };
}

function changeImage(direction, galleryId) {
  const galleryGrid = document.getElementById(`${galleryId}-grid`);
  const images = Array.from(galleryGrid.querySelectorAll("img")).map(
    (img) => img.src
  );

  currentIndex = (currentIndex + direction + images.length) % images.length;

  // Update the modal image
  const modalImage = document.getElementById(`${galleryId}-modalImage`);
  modalImage.src = images[currentIndex];
}

function closeModal(galleryId) {
  const modal = document.getElementById(`${galleryId}-modal`);
  if (modal) {
    modal.style.display = "none";
  }
}
